### ISSUE TITLE
Translations support 

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1300]
Meta-issue to organize progress, will be done in series of PR to avoid large amount of changes at once

**Progress**
- PR #1293 - everything related to Launcher

**Functionality**:
- [x] Implement translations for Launcher using Qt translator
- [ ] Implement translations for Map Editor using Qt translator
- [x] Allow mods to define mod information (e.g. name/description) with localization to current language of Launcher
- [ ] Provide mechanism to translate data from H3 files via mods that is better than direct editing of H3 files
- [ ] (optional/needs research) Provide mechanism to translate .h3m and .h3c files.
- [ ] Integrate existing translate.json into H3 translation support
- [ ] Provide mechanism for mods to translate new content
- [ ] Multiplayer support - ensure that client & server can run with different languages

**Languages**:
- [x] English (already available)
- [x] Ukrainian (done by me)
- [x] German (In progress, by [Laserlicht](https://github.com/Laserlicht))
- [ ] Polish (proposed by dydzio)
- [ ] Russian
- [ ] Any other languages?

**Translation assistance**
If there is anyone willing to provide missing/new translation ask me here or on Slack. What I will need is following:

- Translation of existing vcmi strings from [here](https://github.com/IvanSavenko/vcmi/blob/translate_launcher/config/translate.json) (they may already be translated somewhere in some mod)
- Translation of launcher strings.
If you have Qt Creator installed you can open [this](https://gist.github.com/IvanSavenko/9c2ed77c18b0d9c13c914f7c986906bd) file in Qt Linguist for nicer UI. 
Or you can edit file manually, [Ukrainian translated file](https://github.com/IvanSavenko/vcmi/blob/translate_launcher/launcher/translation/launcher_uk.ts) may be more suitable in this case - it has English strings included.
- Translation of Map Editor - not exported yet

**Comment by heroesiiifan** [comment]
Hi @IvanSavenko 

First of all, thank you for your effort of a better language support.

For [german-translation](https://github.com/vcmi-mods/german-translation) I have a few questions:
* how is it thought in the future with the translate.json? Do we maintain the foreign languages directly in the source of VCMI? Have a current file (Can be intigrated into VCMI with pleasure). But with the current state it can't load via a mod (don't know why though).
* What about the bonuses_texts.json? Doesn't it need to be replaced as well?
* In my case I would leave the translated TXT as they are, they should still load without problems (regardless of the new option), right?
* Can we make it so that when you select "German" in the launcher the translation mod is automatically installed? Or how should we do it for cases without official translation?

**Comment by IvanSavenko** [comment]
Hi.

> how is it thought in the future with the translate.json?

Current plan - is to have translate.json for all languages in vcmi repo, specifically - as part of integrated "vcmi" mod. Since I am planning to add support for translation of mods, it makes sense to reuse this functionality and integrate translation of vcmi strings into vcmi mod and have them auto-selected based on language selected by user/autodetected by game.

(Yes, format of translate.json was changed in recent PR, so it won't load as it. I already have fixed version for German and few other languages, but have not uploaded it anywhere yet)

>What about the bonuses_texts.json? Doesn't it need to be replaced as well?

Yes, eventually. I still have quite long list of things to do for translations.
Current plan is to merge its content into translate.json (and any other stray untranslated strings we have in vcmi)
I see this file in your mod, so will integrate it into translation once I get to this part.

>In my case I would leave the translated TXT as they are, they should still load without problems (regardless of the new option), right?

Yes, they can load without problems. In fact, with #1399 game will also automatically detect German install (whether in form of your mod or some custom H3 install).

Whether you switch to this "new option" is up to you. Generally speaking, conversion should be trivial. VCMI will be able to generate json output of loaded text which you can copy-paste into a mod. 

Main reasoning behind this option was: 
- H3 txt files have rather specific format, which inexperienced translator can be easily break
- Translation of maps & campaigns is impossible without providing entire map/campaign & you need to search for translatable strings all over the map.
- In multiplayer, all texts from map will be taken from host player who may use different language.

>Can we make it so that when you select "German" in the launcher the translation mod is automatically installed? Or how should we do it for cases without official translation?

Yes, I am considering this. Although not fully automatic. My current plan is to have user select desired language of vcmi itself (e.g. for Launcher) and, if language of detected H3 install is different - provide option to install translation mod in one click, without search through repository.

**Comment by heroesiiifan** [comment]
I've tested the Mod-Translation.

Seems to work without problems: https://github.com/vcmi-mods/cathedral-town/pull/1

**Comment by IvanSavenko** [comment]
Not exactly fully supported yet - I'd like to have some "validation", that will automatically report strings to translate.
Still, great to see its first usage. Glad that it works. Haven't tested much apart from UI texts.

**Comment by heroesiiifan** [comment]
Hi @IvanSavenko:
I have brought the german translation up to date.

I have created a [vcmi-1.2 branch](https://github.com/vcmi-mods/german-translation/tree/vcmi-1.2). Is there actually a way that the mod manager in the development build falls back on it and not on the master?

Otherwise I still have a few questions:
- if I have understood correctly, then the H3M support is complete? I get with "convert txt" but unfortunately only a few strings out (map name, decriptions, etc.), but for example no events. How do I get that?
- H3C is not support yet, right?

**Comment by IvanSavenko** [comment]
Hi @heroesiiifan . I think we're using this file for mods that require daily builds version: https://github.com/vcmi/vcmi-mods-repository/blob/develop/beta.json 
Once you have your mod in there you can add this URL as second mod repository in settings.

As for your questions:
- H3M support itself is done, but yeah, no way to export without modifying source code. Will add h3m export to `convert txt`
- H3C - untested. Strictly speaking - it may work since h3c is largely collection of h3m maps, but not something I tested yet and so far no way to generate translations using existing h3c files.
- Current plan (hopefully will implement next week) is that mods of type "translation" will be only active if currently selected language matches mod language. So as long as the game views your mod as "translation to german" it will automatically enable/disable it based on selected language,

And by the way - please add `"language" : "german"` into your mod.json. This field will be used to detect translations and as a way to detect encoding of h3m/h3c/txt/fnt files (this part not applicable to German though - looks like English & German use same encoding anyway)

**Comment by heroesiiifan** [comment]
>     * H3M support itself is done, but yeah, no way to export without modifying source code. Will add h3m export to `convert txt`
>     * H3C - untested. Strictly speaking - it may work since h3c is largely collection of h3m maps, but not something I tested yet and so far no way to generate translations using existing h3c files.

Would be really nice if we could export these too.

> And by the way - please add `"language" : "german"` into your mod.json. This field will be used to detect translations and as a way to detect encoding of h3m/h3c/txt/fnt files (this part not applicable to German though - looks like English & German use same encoding anyway)

done :)

**Comment by IvanSavenko** [comment]
> Would be really nice if we could export these too.

Yep, planned, worst-case scenario - will be done for 1.2.1

All in all my TODO list so far is:
- Do not load translation mods if language selected by player is different from mod language. Meaning, as long as player has German Translation mod and this mod was not explicitly disabled by player it will be only loaded if game language set to German.
- Propose to install translation mod during initial setup if detected H3 language is different from language selected by player. Meaning, if player has English H3, but selects German during setup, he should be offered to install German Translation mod.
- Add similar option whenever player changes language in settings.
- Integrate text export from h3m into "convert txt".
- Integrate text export from h3c into "convert txt". Ensure that h3c translations work.
- Show list of languages supported by mods in Launcher
- Find English strings embedded in vcmi json's and make sure that they are translated. Example: creature bank names.

More long-term TODO's, potentially for 1.3:
- Translation support for VCMI map format.
- Translation support for multiplayer - game should select all texts, both from H3M (e.g. events) and from game state (e.g. hero/creature names) based on language of local player, not language of host player.

**Comment by tytannial** [comment]
Hi, is there any plan to make a converter or importer for game locale file, which imports the txt/map files, and encode them with utf8. Also provide an option using utf8 as game encoding.

**Comment by kambala-decapitator** [comment]
user reported issue with Russian language in 1.2.1/1.3: https://forum.vcmi.eu/t/russian-thread/357/837?u=kambala (check also the full conversation)

**Comment by IvanSavenko** [comment]
@kambala-decapitator 
Not sure what's going on there...

According to your log - he has English text files - pretty much exact match. 
Not Chinese or Russian.
Logs should say something like "Comparing to Engilsh: 0.0002" - value closest to 0 is the one that is detected.

However it is possible that his H3 copy has different files layout that vcmi is not aware of and because of that localized text files were not found.
For example in English version .txt files are in 'H3bitmap.lod' but in Polish they are in 'h3abp_bm.lod', which vcmi was ignoring before fix.

**Comment by heroesiiifan** [comment]
Another small addition for the todo: Support VCMP Campaign format

Even if I don't know if this is already actively in use.

**Comment by heroesiiifan** [comment]
Maybe also add moat names to english.json instead of moats.json.
To able to clearly translate.

**Comment by GeorgeK1ng** [comment]
VMAP can't be translated by mod and map needs to be edited. No idea about VCMP, have not tried covert H3C -> VCMP, but I think it will be same. Require VMAP to be edited with translations. Othewise it looks like all places are fine, have not currently encountered any issue and Czech translations works as expected in all places.

**Comment by GeorgeK1ng** [comment]
Or if they should be translated by mods /translate or /translate maps commands not exporting these strings.

**Comment by GeorgeK1ng** [comment]
Yes, but accessing them using Map Editor is not comfortable. Much better is to extract english.json and inject it back as czech.json when translated.
And it also require touching map file itself. In my opition it's step back. Of course it's fine to have multilanguage maps. But support loading these string from mods and allowing their extraction using /translate commands will fit whole translation logic better.

**Comment by IvanSavenko** [comment]
Not really sure what prevents these strings from being exported for translations. Don't see anything that would explicitly block them.

Author of map editor / vmap translations insisted on this approach, with in-editor translations. It has the advantage of allowing distribution of maps as a single file, but that's not how we distribute them in practice, so not sure.

Don't see anything wrong with allowing usual translation export for vmap's as well

**Comment by GeorgeK1ng** [comment]
Idea is fine to allow distributing standalone maps. But allow loading their translations in same logic as h3m / h3c will be great
For example here we have vmap, which I translated by adding czech.json. https://github.com/vcmi-mods/newtown-terrains/tree/vcmi-1.6/newtown-terrains/Mods/icelandTerrain/content/Maps
