### ISSUE TITLE
Competitive multiplayer feature requests

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1361]
Comprehensive list of all multiplayer-related features requested by players.

Major tasks:
- [ ] #1133 
- - [ ] #1173 - potential solution to slow hero movement
- [ ] Introduce player ranking for game lobby
- [ ] #1364
- [ ] Simultaneous turns support
- [ ] #1947 
- [ ] #818 

Minor improvements:
- [ ] #1352
- [x] #1170 
- [x] #1171 
- [ ] Heroes available in taverns should have their movement points reset to default value based on their creatures
this is likely H3 bug, not applicable to vcmi, but needs rechecking
- [ ] Defeated heroes with high levels should not reappear in taverns. Possible solutions:
- - [ ] Tavern hero selection should always pick heroes with lowest level among heroes in pool
- - [ ] If hero is defeated and not re-recruited after surrender, all its stats & artifacts will be reset to initial values

Balancing (should be done in mods, but may need engine support first):
- [ ] Town portal and dimension door are guaranteed with 4-th mage guild reroll
check HotA guild reset mechanics for details
- [ ] T1 & T2 creature specialists should not appear as second hero in tavern
- [ ] Straker, Ufretin and Piquedram should not appear in tavern on the first day
- [ ] modifications in artifact classes: decrease bullshit relics, increase value of some OP artifacts like bots of speed or cape of velocity

**Comment by Povelitelh3** [comment]
For online games it will be very important https://bugs.vcmi.eu/view.php?id=2603

**Comment by IvanSavenko** [comment]
Closing, all items were moved to MP project: https://github.com/orgs/vcmi/projects/5
