### ISSUE TITLE
HotA supported features

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1614]
This is a compilation of all stuff HotA mod offers. A comprehensive list, that can shows what VCMI already covers and what still needs to be developed.

This list is based on original HotA official feature list: https://h3hota.com/en/documentation

# Cove faction

## Cove Town
- [x] Creatures
Nix Revenge not implemented
Sea Witches and Sorceresses abilities work somewhat different
- [x] Cannon
- [x] Hero Classes
- [ ] Heroes
- [ ] Grail
- [x] Adventure Map Dwellings

### Adventure map
- [ ] Spell Research
- [ ] Towns with Fort always have level 2 dwelling built by default.
- [ ] Heroes with a starting army always have all troops (and a war machine)
- [ ] If both heroes die (not retreated or surrendered) as a result of a battle, they will not turn up in taverns, unless all other ones have become unavailable.
- [ ] Dwellings belonging to players accumulate creatures each week. Number of creatures in dwellings without owner is set to one creature growth each week.
- [ ] On standard random map templates monsters join hero only for money and only half of group is joined for the cost of the whole group.

### Combat
- [ ] On most of random map templates works the combat round limit: 100 rounds. 
Any battle involving a player and lasting more than 100 rounds will be forcibly terminated. The attacking player will be invited to retreat, surrender, or end with quick combat. The availability of retreat and surrender depends on whether they were available in the first place (except Shackles of War are now ignored). Quick combat is only available in a battle against AI. During finishing with the quick combat a hero of the human player does not cast spells.
- [ ] Some creatures can perform alternative action. Use interface button or Alt key for switch.
- [ ] Shooting creatures can perform melee attack instead of shot.
- [ ] Harpies and Harpy Hags can attack without return.
- [ ] Faerie Dragons can attack instead to spell cast.
- [ ] Archangels and Pit Lords can move to hex instead to corpse resurrect from it.
- [ ] Added the possibility for 2 hex wide creatures to move back 1 hex.
- [ ] Negative luck was introduced.
While under effects of negative luck the stack has a chance (-1: 1/12 -2: 1/6, -3: 1/4) to cause half the damage. Hourglass of the Evil Hour neutralizes luck only if it is positive
- [ ] The creatures in battle without a hero can now be subjected to the effect of good and bad luck. Originally luck never worked for creatures with no hero, even if it was positive (or negative) for them.
- [ ] New highlands terrain added.
No movement penalty.
Highlands is native terrain for Conflux creatures.
Objects that appear on highlands on random maps (besides all-terrain ones):
(Trading Post, Garden of Revelation, Medusa Stores, Faerie Ring, Mineral Spring, Ruins Hermit’s, Shack, Gazebo, Junkman)
- [ ] New wasteland terrain added.
Movement penalty 125%.
Objects that appear on wasteland on random maps (besides all-terrain ones):
(Medusa Stores, Derrick, Warlock’s Lab, Prospector, Trailblazer, Grave)
- [ ] Native terrain bonus on the underground depends on the particular terrain (originally it was always considered subterranean)

#### Creatures

- [ ] Slightly increased the AI Value of Monk (Random Map Generator was underestimating them when placing). Thus, Pandora Boxes and Seer Huts on random map will give 25 Monks, instead of 30.
- [ ] Increased the AI Value of Efreet Sultans (for decreasing their count in guards on random maps). Thus, Pandora Boxes and Seer Huts on random map will give 8 Efreet Sultans, instead of 12.
- [ ] Fire immunity of Firebirds replaced with 50% Fire Resist. Thus, slightly decreased their AI Value (Pandora Boxes and Seer Huts on random map will give 6 Firebirds, instead of 5).
- [ ] Largely increased the AI Value of Fairy Dragon. Their amount on random maps is now about 1.5 times lower.
- [ ] Arrow Towers ignores the target’s defense completely (also, fixed various bugs with incorrect damage calculation). Attention: the Arrow Tower attack is 10 and defending hero attack and archery skill work for Arrow Tower. That is why the result damage of Arrow Tower is significantly greater than in original game, is which the Arrow Tower attack was counted as 0 and hero skills did not affected its damage.

#### Artifacts

- [ ] Orb of Inhibition and Recanter’s Cloak are banned by default.
- [ ] Garniture of Interference, Surcoat of Counterpoise, and Boots of Polarity are disabled by default.
- [ ] Shackles of War effect applies only when both sides in the battle have heroes.
- [ ] Movement points given by Equestrian’s Gloves, are reduced from 300 to 200.
- [ ] Movement points given by Boots of Speed, are reduced from 600 to 400.

#### Spells

- [ ] Advanced and Expert Slow reduces the speed by the formula (old speed x 0.5 + 1), rounding down.
- [ ] The damage of Armageddon spell reduced form 50*(spell power) + 30/30/60/120 to 40*(spell power) + 30/30/60/120.
- [ ] The effect of Protection from Air, Protection from Fire, Protection from Water, and Protection from Earth spells increased from 30%–30%–50%–50% to 50%–50–%75–%75%.
- [ ] Fly, Water Walk and Dimension Door spell changes which make it impossible to trigger objects without alerting the guard even while using these spells (if take into account fix of object guard tilting bug).
- [ ] To trigger a guarded object while flying or water walking (if the object in question is not a freely passable one, like a friendly Garrison), you will now have to first land on an adjacent tile and fight the guardians.
- [ ] If a hero moves to a guarded tile after casting the Dimension Door, combat will start. Casting cursor will change its appearance if that’s the case.
- [ ] Fixed bugs with interruption the flight on forbidden cells. Interrupting the flight above a guarded tile will now trigger combat.
- [ ] Fly cast works when hero wears Angel Wings or has lower level Fly effect.

#### Skills
- [ ] Resistance skill is disabled by default.
- [ ] Added Interference skill: reduces enemy hero spell power during combat by 10%–20%–30%. Enemy spell power is rounded down, but cannot become less than 1.
- [ ] Scouting skill now adds +1/+3/+5 cells to hero sight radius instead of +1/+2+/3.
- [ ] Necromancy raises 5%–10%–15% enemy’s dead as Skeletons instead of 10%–20%–30%.
- [ ] Logistics increases hero movement points by 5%–10%–20% instead of 10%–20%–30%.
- [ ] Intelligence increases hero spell points by 20%–35%–50% instead of 25%–50%–100%.
- [ ] Mysticism refills 5–10–15 mana every day instead of 2–3–4.
- [ ] Estates gives 250–500–1000 gold every day instead of 125–250–500.

# Adventure map Objects
## Changes to original objects
- [ ] Player can refuse to learn Witch Hut or Scholar secondary skill.
- [ ] If a creature has multiple external dwellings (not counting multi-dwellings), each of the succeeding ones will be generated less frequently.
- [ ] Cartographer Maps cost 10000 instead of the former 1000. Cartographers are not generated on random maps.
- [x] Keymaster Tents were removed from random generation.
- [x] Seer Huts cannot require artifacts that are part of a combination artifact.
- [ ] Sanctuary now will not be spawning on randomly generated maps.
- [ ] Trading Post value is increased from 100 to 3000.
- [ ] The value of the Obelisk is reduced from 3500 to 350. Added a restriction of no more than 1 Obelisk in the zone.
- [x] Only 1 Den of Thieves and only 1 Tavern now allowed per zone.
- [ ] Density of Shrine of Magic Incantation and Shrine of Magic Thought is reduced from 100 to 50.
- [ ] Changes to Spell Scrolls.
The value of the scroll level 4 increased from 4000 to 8000. Removed Town Portal and Waterwalk spells.
The value of the scroll level 5 increased from 5000 to 10000. Removed Fly and Dimesion Door spells.
Added srcoll with Town Portal, Fly, Dimesion Door and (in case of water map) Waterwalk. Value 20000, frequency of occurrence 30, maximum 1 in the zone.
Added restrictions on the maximum number of scrolls in the zone.
Scroll Level 1: 6.
Scroll Level 2: 5.
Scroll Level 3: 4.
Scroll Level 4: 3.
Scroll Level 5: 2.
The mechanism of a uniform distribution of spells in the scrolls: Map will always have about the same number of scrolls with all the spells of the same level, and scrolls with the same spells are less likely to be near each other.
- [x] Elemental Conflux (multi-dwelling on map) gives +1 to the increase in air, water, fire and earth elementals in all towns, not just the air elementals.

## Following objects from original game are now generated on random maps:
- [x] Golem Factory. Allows to recruit Stone, Iron, Gold and Diamond Golems. Value around 4500, density 20, generated both in Neutral zones and in Tower zones.
- [x] Elemental Conflux. Allows to recruit Air, Water, Fire and Earth Elementals. Value around 6000, density 20.
- [x] Freelancer’s Guild. Allows to trade units for resources. Value 100, density 50, all dry land terrains, limit of 1 per zone.
- [ ] The Crypt, Derelict Ship and Shipwreck shows the approximate number of foes after the visit. When you visit any of these objects, morale is reduced immediately if it was previously looted, without a window.
- [ ] The number of Peasants in Pandora Boxes and Seer Huts decreased to 150 (the value is unchanged).
- [ ] Value of Estate (Vampires outer dwell) multiplied by 3 (from around 3000 to around 9000).
- [ ] Value of Hovel (Peasant outer dwell) multiplied by 3, so they will not appear more often than another level 1 Dwellings.
- [x] The image of every town depends on its Fort level (no Fort — Fort — Citadel — Castle — Castle+Capitol).

# Interface
## In-battle interface
- [ ] The choice of battle speed is widened up to 5 options.
- [ ] Fixed interface for selecting spell target for hero and creatures.
- [ ] Cast activation button changed for Fairy Dragons from F to G.
- [ ] Information about current spell duration is added into view creature window and creature mouse-over statistics.
- [ ] Additional hints has been introduced to be displayed when targeting a stack.
- [ ] Information about possible number of killed creatures added to possible damage.
- [ ] The effect of damage spells, healing and resurrection spells (both for hero and caster creatures) is shown.
- [ ] The effect of First Aid Tent healing is shown.
- [x] The number of remaining shots for caster creatures is shown.
- [ ] Hero sprites now depend on their class and gender.

## Map interface
- [ ] In online play, it is now possible to plan your heroes’ movement during your enemy’s turn (like during your turn).
- [ ] Hold Alt and hover over an adventure map square to see a hint stating how long it will take your selected hero to arrive there.
- [ ] Hold Shift and click a hero on the map to select him, even if another hero has already been selected.
- [ ] Various fixes of path length and hero maximum movement point calculation.
- [ ] When visiting creature banks, information about the guards was added, if it can be seen by clicking the right mouse or via dragging the mouse over the information window.
- [ ] Added display of creatures available for hire in the window by clicking the right mouse button, the hint by pointing mouse and an external window when visiting the dwelling, owned by yourself or an ally.
- [ ] Last player to visit the Black Market can review its inventory.
- [ ] The player can review the creatures of the Refugee Camp the week it was last visited.
- [ ] Improved Hero route (Added a new route color (dark-red) that shows where the player would not arrive even with full movement pool)
- [ ] Added dynamically calculated effect summary in many spell descriptions
- [ ] Added numeric descriptions of armies’ approximate size.
- [ ] Heroes can be dismissed in towns and in Kingdom Overview screen
- [ ] Added the hero exchange button on a city screen (hotkey E).
- [ ] Added a hint with the creature upgrade cost for the upgrade button in creature window, even if the button is inactive
- [ ] The dialog to buy a Spellbook is now displayed on the Mage Guild screen.
- [ ] Added the option to disable background sounds in the adventure map (System Options Menu): the sounds of a new day, week and month, the sound of the battle, the background sounds and the sounds of site visits.
- [x] Added support of new map sizes: H (180x180), XH (216x216), G (252x252).
- [ ] The way of map winning score calculation was changed. Now it is harder to get higher ranks.

# RMG
- [ ] Water elements were excluded from random maps without water.
- [ ] Changed the list of possible factions to set the one for dwellings, Pandora’s boxes and Seer’s huts for the zone without town, depending on the type of area

# Other
- [ ] Naga Bank gives gems instead of sulfur as a reward
- [x] Fixed incorrect intervals between offers to take Wisdom and Air/Water/Fire/Earth Magic for Elementalist.
Earlier Elementalist was offered Wisdom no later than 6 levels after the previous offer, and the all types of Magic were offered every 4 as for all Might heroes. Now Wisdom and all types of Magic are offered no later than level 3, as for all Magic Heroes.
- [ ] Badge of Courage no more gives mind spell immunity.
- [ ] Starting skills: Uland’s Wisdom and Deemer’s Scouting — downgraded from Adv. to Basic (each of them has 2 starting skills).
- [x] Roland’s specialty now affects Swordsmen and not only Crusaders.
- [ ] University does not offer necromancy anymore.
- [ ] Fixed non-centered images of monsters on map.

# Map Editor
- [ ] Users can enable or disable monster weeks and months
- [ ] Users can set a restriction on the combat duration
- [ ] Users can customize creature banks: bank level, reward artifacts, and the presence or absence of an upgraded monster stack
- [ ] Extra settings for monsters:
- [ ] Fine tuning of the mood in addition to the standard settings; a range of randomly selected moods can be specified.
- [ ] Specifying whether monsters join for money only or can join for free.
- [ ] Specifying the percentage of monsters joining: users can set what percentage of the monster group will be added to the player’s army if they join. The remaining monsters will disband. If monsters join for money, the full price for the group will be paid anyway.
- [ ] Specifying the number of stacks into which monsters are divided in combat.
- [ ] Specifying the presence or absence of an upgraded monster stack in combat.
- [ ] Local Events can be independently configured for triggering by human and AI-controlled players
- [ ] A new object, the Quest Gate, that requires completing a quest to pass and does not disappear after the quest is completed
- [ ] Users can set multiple quests for one Seer Hut: a sequence of one-off quests or a recurring quest sequence
- [ ] Arena mode
The new Arena mode has been introduced in HotA, where eash game is essentially a single combat between heroes. The composition of the heroes’ armies, their skills and spells and other combat parameters are set in the map. The map may also provide for the players to choose certain settings for their heroes.

### Other
- [x] Native terrain changed to highlands.

# New neutral creatures
- [ ] Leprechaun
- [ ] Satyr
- [ ] Steel Golem
- [ ] Fangarm

# New artifacts
- [ ] Diplomats Cloak
- [ ] Ironfist of the Ogre
- [ ] Golden Goose
- [x] Trident of Dominion
- [x] Shield of Naval Glory
- [x] Royal Armor of Nix
- [x] Crown of the Five Seas
- [ ] Wayfarer’s Boots
- [x] Ring of Supression
- [x] Hideous Mask
- [x] Pendant of Downfall
- [x] Runes of Imminency
- [x] Demon’s Horseshoe
- [x] Shaman’s Puppet
- [ ] Ring of Oblivion
- [ ] Cape of Silence
- [ ] Charm of Eclipse
- [ ] Seal of Sunset
- [ ] Plate of Dying Light
Not for random maps. These artifacts do not appear on random maps until they are enabled in the template settings.
- [ ] Pendant of Reflection
- [ ] Horn of the Abyss

## New creature banks
- [x] Experimental Shop
- [x] Wolf Raider Picket
- [x] Red Tower
- [ ] Black Tower
- [x] Churchyard
- [x] Mansion
- [ ] Ruins

### Sea objects
- [x] Beholders’ Sanctuary
- [ ] Temple of the Sea
- [ ] Pirate Cavern
- [ ] Ivory Tower
- [ ] Spit

## New Adventure Map objects
- [x] Warehouses (wood, mercury, ore, sulfur, crystals, gems, gold)
- [ ] New Hill Fort
- [x] Shrine of Magic Mystery
- [ ] Cannon Yard
- [ ] Temple of Loyalty
- [ ] Skeleton Transformer
- [x] Colosseum of the Magi
- [ ] Watering Place
- [ ] Town Gate
- [ ] Mineral Spring
- [ ] Hermit’s Shack
- [ ] Gazebo
- [ ] Junkman
- [ ] Derrick
- [ ] Warlock’s Lab
- [ ] Prospector
- [ ] Trailblazer
- [ ] Grave
- [x] Monoliths (Added 12 new Two Way Monoliths)

### Sea objects
- [x] Sea Barrel
- [x] Jetsam
- [x] Vial of Mana
- [ ] Seafaring Academy
- [ ] Altar of Mana
- [ ] Observatory
- [ ] Ancient Lamp

# Factions gameplay changes
### Heroes
- [ ] Sir Mullich is banned by default. Lord Haart available instead.
- [ ] Sylvia is banned on maps without water. New hero — Beatrice available instead

## Rampart
- [ ] Heroes’ starting armies amount of Elves decreased from 3–6 to 2–4.

### Heroes
- [ ] Ufretin starting skill was changed from Resistance to Interference.
- [ ] Clancy starting skill was changed from Resistance to Interference.
- [ ] Thorgrim is banned by default. New hero — Giselle available instead
- [ ] Gem has the starting Spell changed on random maps without water from Summon Boat to Bless.

### Building tree
- [ ] Altar of Wishes, Golden Pavilion, Upg. Golden Pavilion, Cloud Temple and Upg. Cloud Temple no longer require Mage Guild level 1 and Mage Tower.
- [ ] Golden Pavilion and Upg. Golden Pavilion now require Altar of Wishes.
- [ ] Upg. Altar of Wishes no longer requires Mage Tower (Mage Guild level one is still required).

### Building prices
- [ ] Golem Factory price in gold is decreased from 2000 to 1500.
- [ ] Upg. Golem Factory price in gold is decreased from 2000 to 1500.
- [ ] Mage Tower price in gold is decreased from 2500 to 2000.
- [ ] Altar of Wishes price in gold is decreased from 3000 to 2500.
- [ ] Upg. Cloud Temple price in gold is decreased from 25000 to 20000.

### Heroes’ starting armies
- [ ] Amount of Stone Gargoyles increased from 3–5 to 5–7.
- [ ] Amount of Stone Golems increased from 2–3 (or 2 in Josephine’s second slot) to 4–5.
### Heroes
- [ ] Fafner starting skill was changed from Resistance to Interference.

### Building tree
- [ ] Upg. Hell Hole no longer requires Mage Guild level 2 (still requires Mage Guild level 1).

### Building prices
- [ ] Brimstone Stormclouds price in sulfur decreased from 5 to 4.
- [ ] Upg. Hall of Sins price in mercury decreased from 5 to 4.
- [ ] Upg. Kennels price in sulfur decreased from 5 to 4.

### Creatures
- [ ] Magogs can shoot fireball at any hex of the battlefield except for its own hex and adjascent ones (unless sniper bow is present). Targeting dialogue is called by pressing G. However, creatures immune to fire can be damaged only by a central hex.
- [ ] Arch Devil decreases Luck by 2 (instead of 1 from the original).

### Heroes’ starting armies
- [ ] Amount of Imps increased from 15–25 to 20–30.

### Heroes
- [ ] Ignatius starting skill was changed from Resistance to Interference.

## Necropolis
- [ ] Necromancy
The amount of skeletons raised by necromancy is halved.
Necromancy raise 5%–10%–15% enemy’s dead as Skeletons instead of 10%–20%–30%.
Amulet of the Undertaker increases Necromancy skill by 2.5% instead of 5%, Vampire’s Cowl — 5% instead of 10%, Dead Man’s Boots — 7.5% instead of 15%. Cloak of the Undead King raise 15% enemy’s dead as Skeletons instead of 30%.
Necromancy Amplifier increases Necromancy skill by 5% instead of 10%.
Number of Skeletons raised by the Necromancy skill is now dependent on total number of slain creatures in an enemy army, rather than on numbers of each individual slain stack.

### Building prices
- [ ] Upg. Tomb of Souls price in mercury decreased from 5 to 4.
- [ ] Mausoleum price in ore decreased from 10 to 5, and in sulfur from 10 to 4.
- [ ] Upg. Mausoleum price in sulfur decreased from 5 to 4.

### Creatures
- [ ] Liches and Power Liches can shoot death cloud at any hex of the battlefield except for its own hex and adjascent ones (unless sniper bow is present). Targeting dialogue is called by pressing G.

### Heroes
- [ ] Straker starting skill was changed from Resistance to Interference.
- [ ] Galthran is banned by default. New hero — Ranloo is available instead

### Heroes’ starting armies
- [ ] Amount of Troglodytes decreased from 30–40 to 20–30.
- [ ] Amount of Harpies increased from 4–6 to 6–8.

### Heroes
- [ ] Ajit starting skill was changed from Resistance to Interference.

### Building prices
- [ ] Cyclops Cave price does not include crystals. Upg. Cyclops Cave price in crystals increased from 0 to 10.

### Heroes
- [ ] Krellion starting skill was changed from Resistance to Interference.
- [ ] Saurug starting skill was changed from Resistance to Interference.

### Heroes’ starting armies
- [ ] Amount of Gnolls increased from 10–20 to 15–25.
- [ ] Amount of Serpent Flies increased from 2–4 to 3–4.

### Heroes
- [ ] Bron starting skill was changed from Resistance to Interference.
- [ ] Woy banned on maps without water. New hero — Kinkeria available instead

## Conflux
- [ ] Growth of Firebirds and Phoenixes decreased to 1 (2 after the construction of Castle).

### Building tree
- [ ] Constructing Upg. Magic Lantern now requires Mage Guild level 1 and Magic University beforehand.
- [ ] New structure Vault of Ashes
- [ ] Cost: 5000 gold, 5 mercury.
- [ ] Requirements: Fort, Mage Guild Level 1, Magic Lantern, Altar of Air, Altar of Water, Altar of Fire, Altar of Earth, Altar of Thought, Pyre.
- [ ] Increases the growth of the Firebird and Phoenix by 1.

### Building prices
- [ ] Cost of constructing the Pyre went up from 10 to 20 mercury and from 10000 to 15000 gold.

### Building properties
- [ ] Aurora Borealis (Grail structure of Conflux) allows learning spells up to according level of the Mage Guild in the city only and doesn’t allow learning spells not available for this town.

### Creatures
- [ ] Fire immunity of Firebirds replaced with 50% Fire Resist. Slightly decreased AI Value (thus, Pandora Boxes and Seer Huts on random map will give 6 Firebirds, instead of 5).

### Creature prices
- [ ] Cost of Psychic Elementals increased from 750 to 950 gold.
- [ ] Cost of Magic Elementals increased from 800 to 1200 gold.
- [ ] Cost of Firebirds increased from 1500 to 2000.
- [ ] Cost of Phoenixes increased from 2000 gold + 1 mercury to 3000 gold + 1 mercury.

**Comment by krs0** [comment]
Issue generated from this documentation:
[HotA 1.6.1 documentation webpage.zip](https://github.com/vcmi/vcmi/files/10833714/HotA.1.6.1.documentation.webpage.zip)

**Comment by rilian-la-te** [comment]
What features are supported by HOTA mod now?

**Comment by krs0** [comment]
Needs to be investigated and checked out in the issue.

**Comment by rilian-la-te** [comment]
@krs, please split it to mod features and engine features. Maybe I will do some of engine features.

**Comment by misiokles** [comment]
Not all creatues should be 'ticked'. Some abilities are misssing (f.e. Nix' Revenge) and some abilities works slighlty diffirent (Sorceresses)

**Comment by misiokles** [comment]
Grail works, some heroes abilities work diffirently, not all Cove buildings work, the same for artifacts.

**Comment by misiokles** [comment]
Yes.

**Comment by rilian-la-te** [comment]
@misiokles so, it works both as artifact and as a creature?

**Comment by rilian-la-te** [comment]
@misiokles how it works? there is many hardcoded features in VCMI now related to ballista, how cannon can override them? I do not find anything in json yet.

**Comment by misiokles** [comment]
It's complicated. It's easy to set cannon as war machine to Cove, and it's easy to but a cannon IF there's empty cannon/ballista slot. Problems occur when you're trying to swap cannon/ballista. But I really don't know how skills affect cannon.

**Comment by rilian-la-te** [comment]
@misiokles there is some info at TheLazy. https://heroes.thelazy.net/index.php/War_Machine#Cannon

And it says than we should have some effects from artillery skill for HoTA cannon. #1518 will allow us to do this effects, I hope.

**Comment by misiokles** [comment]
In mods we can find some other war machines (Forge, Grove, Plague Tent)...

**Comment by rilian-la-te** [comment]
@misiokles I waiting to get #1609 to add some more bonuses for making correct war machines)

**Comment by IvanSavenko** [comment]
Probably closing - moved to Github Project
https://github.com/orgs/vcmi/projects/3
