### ISSUE TITLE
Potential configurable objects extensions

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#1751]
Tentative roadmap for extension of RewardableObject/configurable functionality. This is long-term task, and likely only some parts of it will be implemented for 1.3

- [ ] **General changes:**
- - [ ] Rename RewardableObject to ConfigurableObject, to reflect its behavior better and match name used by json's
- - [ ] Rename Reward to Effect, since even now "reward" is not always something positive
- - [x] Implement schema for validation of rewardables. Schema check should be executed by handler during beforeValidate call when final json is generated. All values should have proper descriptions in schema, for potential uses in mod tool.
- - [x] Implement localization support for all texts in configurable objects - right now only H3 objects can be indirectly translated since they use references to strings from H3 text files
- - [x] Implement "scouted" state for objects - if we know of a visit, we should mark object as visited. Windmill should become "scouted" if last visit was done by our or allied hero and display its status (visited/not visited). Visiting of a Windmill by enemy hero *may* reset its scouted status (TODO: recheck H3)
- - [x] Ensure that visited state of single-visit objects (e.g. Corpse/Wagon) is not revealed to all players - if player A visits object, non-allied to him player B should not be able to see that object is now empty
- - [ ] Implement visit confirmation: message that will be shown before visit. Warrior's Tomb should have a message to confirm visit, even if object is already empty or even *known* to be empty.
- - [ ] Implement limiter for number of free slots in backpack and provide fallback rewards for all H3 objects that grant artifacts, as per H3 rules (depends on backpack PR by @SoundSSGood )

 - [x] **Convert creature banks to configurable:**
- - [x] Make object "Guardable". Guards can be defined as part of "reward/effect". Make sure that AI is aware of guards/danger level.
- - [x] Allow defining guards starting position layout: standard or banks
- - [x] Scouted creature banks should show their guards, as per H3 rules
- - [x] Creature banks should have a message to confirm attack on guards, if object is not empty

- [x] **Convert Magic Shrines, Scholars, Witch Huts to configurable:**
- - [x] Implement "variables" that can be shared between limiter and reward. Variables should be defined on object level (or effect level?) and can be used in limiters/effects. For example, Magic Shrine should have a variable of type "spell" and use it in both limiter and effect to generate different message depending on whether hero knows stored spell
- - [x] When scouted, should permanently reveal its content (spell/skill)
- - [x] Objects should be able to load their state from .h3m/.vmap. Probably by initializing their variables?
- - [x] Make sure that it is possible to implement "refusal" for Scholar/Witch Hut in a way similar to HotA or HD Mod (can't remember which) to allow such functionality in mod.

- [ ] **Evaluate possibility of unifying code with other objects, either in form of converting to configurable or in form of code reuse/shared base class. Rejecting and keeping them as separate class is also an option:**
- - [x] Events / Pandora boxes - can be viewed as "raw" configurable object that has its entire configuration in map
- - [x] Seer Hut - can be viewed as special case of configurable that has different limiter, connected to map object(s), but with standard effect.
- - [ ] Dwellings - while "base" dwellings can be kept as it, complex logic of Refugee Camp / War Machine Factory might be better represented as configurable
- - [ ] Sign/bottle - configurable object that only has a single message
- - [ ] Sirens - probably too special handling to be converted to "rewardable".
- - [ ] Resources and artifacts - probably too "low-level" to be converted to rewardable and should be better kept separately

Related issues:
- #910 
- #1289 
- #1752

**Comment by rilian-la-te** [comment]
I want to implement some parts of this. Resources can be converted to configurable AFAIK, when guards will be implemented. Because campfire is also such low level, but it is a rewardable already. Artifacts - agree with you.

**Comment by IvanSavenko** [comment]
@rilian-la-te 
If you wish to - sure. Ping me before you take anything, to avoid duplicating work accidentally. I'll probably also write before taking anything from this issue.

However I likely won't work on anything from this list for quite some time, with possible exception of localization support.

Converting resources - I don't know... For now I am somewhat against it. This  *might* make sense from code unification point of view, but right now I view them as too integrated into game mechanics. For now let's leave them for later and implement more important tasks from this issue first. I would rather consider configurable/moddable resources first, before attempting replacing resource piles with configurable.

For example, creature banks & witch hut / shrines is something that modders might want to actively use, but resources conversion won't give any "interesting" results.

**Comment by rilian-la-te** [comment]
@IvanSavenko resource piles is not very integrated into game mechanics (not resources itself, but piles on map). But for code unification - it is very good.  I think after adding guardables resources conversion will be done almost automatically.

**Comment by IvanSavenko** [comment]
Maybe. But for now I think priority should be:
- everything from "general" section
- creature banks and Witch Hut/Scholar/Shrine
- and once those are done, consider other objects, e.g. resources.

**Comment by IvanSavenko** [comment]
> maybe it should be implemented after scripting

Right now I think Sirens is probably best to be left for scripting - too special rules. Everything else is quite similar to existing configurable functionality.

> rewardable objects that can have selected details configured per map? 

- Witch Hut / Shrines / Scholar are H3 example of such object.
- Events/Pandoras go even further and have their entire config in map.

**Comment by dydzio0614** [comment]
are you familiar with H4? i think about implementation of h4 bomb object

**Comment by IvanSavenko** [comment]
> are you familiar with H4? i think about implementation of h4 bomb object 

I've heard about that thing from Warmonger, but have never seen anything like that in standard maps/campaigns. Might have missed though.

> and what about map editor support - aren't witch hut / scholar sorta hardcoded?

Right now? Yes. But nothing prevents us from making Witch Hut into configurable object with 1 variable that can be edited in map - skill to grant.

> also expanding seer hut to have part of H4 functionality could be good idea 

Not against it, but rather long-term task IMO - I would rather have other stuff from this issue done first, and keep Seer Hut for later.
This will also require support from editor, so relatively large in scale.

**Comment by dydzio0614** [comment]
so in short... H4 bomb gives powerful tool for mapmakers, allowing to place bomb which acts as sort of coordinate marker, then refer to it from event / seer hut etc. to delete all map objects at that tile (or topmost object - I forgot). Potentially not much work if we allow specifying vector of x/y/z coordinates configurable in map

**Comment by DjWarmonger** [comment]
I think we'll have to handle object state / visibility as a separate feature. Think about allies and AI, but in the future also about spectator mode.
We may also want to change object information details based on some skill / effect or game setting, including debug purposes or watching AI games.
