### ISSUE TITLE
Release 1.2 extra checklist

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1756]
Special things to do for release 1.2:
- [x] Finish everything from [Milestone 1.2](https://github.com/vcmi/vcmi/milestone/4)
- [x] Update changelog with final changes
- [x] Make sure multiplayer lobby works
- [x] Give mods repo permissions to ivan
- [ ] Update github wiki pages: translations modding doc, cheats, client commands, terrain format, not sure about configurable objects, https://github.com/vcmi/vcmi/pull/1764
- [ ] Update other relevant wiki pages if any, for example related to json schema changes
- [x] Make sure ai swap to nullkiller works for android launcher too
- [x] move RMG templates into VCMI essential files - including: rename "multiplayer templates" to something else, make OH3 templates disabled by default due to tendency to produce bugged / low quality maps
- [x] Fix hota mod problem with german language, 
- [x] vcmi-extras extended RMG / changelog mess, 
- [x] change mod repo file naming schema to vcmi-1.2.json
- [x] remove "no battle intro" mods from mod repository + wog submod
- [x] optionally restore "vcmi englisation" mod after packing its content to zip
- [x] optionally disable hero limit in resourceful AI mod by default (there is mod bool flag for this)
- [x] encourage relevant people to do translations update, especially launcher
- [ ] test launcher / settings texts length in various languages
- [ ] test gameplay and random map generator with biggest mods - HotA, WoG, ToW etc.

**Comment by IvanSavenko** [comment]
Also - remove "no battle intro" mod from
1) mod repository
2) wog submod (a thing, apparently)
Redundant since we now have in-game option for that.

**Comment by dydzio0614** [comment]
updated list

**Comment by DjWarmonger** [comment]
Set default AI to NKAI. There was a ticket for that already.

**Comment by IvanSavenko** [comment]
@DjWarmonger yeah, it is in 1.2 milestone

**Comment by IvanSavenko** [comment]
> optionally restore "vcmi englisation" mod after packing its content to zip

Haven't tested yet, but largely done, using 1.2 translation format:
https://github.com/IvanSavenko/h3-for-vcmi-englisation
Don't have write access to main mod repo at the moment, so can't create 1.2 branch.
@nullkiller can you make me member of vcmi-mods organization?

**Comment by IvanSavenko** [comment]
One more potential task: review translations.
@krs0 clearly shown some interest, especially in that "battle-thingy" name.

For example "Skip Intro Music" might be renamed to "Start Battle Instantly" or something to that effect. There might be other options not immediately clear to those outside of team.

**Comment by dydzio0614** [comment]
Yes and no, i think it's reasonable to provide some own terms rather than forcing compatibility with hd mod / hota names for stuff etc.
Current names are probably reasonable in general, and players tend to pick up names provided by developers. I would make this low priority optional task

**Comment by IvanSavenko** [comment]
Not saying that we should use term from Hota/HDMod/whaterver, just recheck that they make sense & consistence.

For example  "Skip Intro Music" option no longer skips music, but allows starting actions while music is still playing.
"Don't wait for intro music" would describe its behavior better, while "Start battle instantly" would describe its intent (which is what player is interested in)

**Comment by dydzio0614** [comment]
well, personally I think old behavior was better - it feels very weird when first thing you see is phoenix rushing at you while music is still playing etc. HotA disables music on pressing ESC

**Comment by IvanSavenko** [comment]
By default this option should be turned off, so phoenix will wait for a keypress. 
Not sure which behavior is better in terms of sound. Instant disabling as we had before felt too abrupt so wasn't great either. Probably fade-out for 0.1-0.2 seconds would've sounded better.

Wasn't aware that hota made such change though.

**Comment by dydzio0614** [comment]
maybe we should add setting or make ESC the only key that removes together with music, optionally with fadeout

**Comment by DjWarmonger** [comment]
As to the last point - I'd like to finally play a full game with latest HotA + ToW + WoG (and some others) when I find time. I think all the features are ready for it.
Just let me fix https://github.com/vcmi-mods/wake-of-gods/pull/3

**Comment by nullkiller** [comment]
Need to check campaigns with a cheat so that we do not release not working campaigns once again)

**Comment by nullkiller** [comment]
And android automatic build preparation for store)

**Comment by Laserlicht** [comment]
@nullkiller 

Nullkiller AI seems also have an problem on latest beta on android:
The setting for the KI is saved in the launcher (same value after app restart). But if you start the game the value is resetted to VCAI in the launcher.

**Comment by danfe** [comment]
At least some versions of FreeBSD exhibit [this bug](https://bugs.vcmi.eu/view.php?id=3146) (looks like it was not transferred to GitHub issues).  Logs did not suggest immediate clues.  If the problem does not manifest itself under GNU/Linux, perhaps the next step would be to try pairing GNU/Linux server with FreeBSD client and/or vice versa.

**Comment by IvanSavenko** [comment]
@danfe Feel free to open this issue here on github.

Not aware of anything like that on Linux systems. And not sure what could be causing it.
- Try checking logs after closing game while in this state ( in XDG_CACHE_HOME, ~/.cache/vcmi/)
- Perhaps try using debugger to find out location of game hang? Might give more info.

**Comment by DjWarmonger** [comment]
> test gameplay and random map generator with biggest mods - HotA, WoG, ToW etc.

I played full game on Coldshadow's Fantasy G with water and all these mods combined.
Also testing RMG with them all the time.

**Comment by DjWarmonger** [comment]
- [ ] Create thread on VCMI forum, like this
- [ ] Add link to this thread to new page (`forumurl`)
