### ISSUE TITLE
VCMI campaigns feature

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1921]
To-do list of features we want to see in VCMI campaigns:
- [ ] Refactor campaign with proper handler and individual parsers for h3m and vcmp formats (no bitmaps, special enums, etc)
- [x] Allow monsters and artifacts from mods to be kept (now limited with std::array sizes)
- [ ] Make some mechanism to encapsulate all campaign-related data (maps, maybe music, etc)
- [x] No indexes for campaign backgrounds and regions
- [ ] Introduce saving of campaign state: carryover heroes between campaigns feature
- [ ] Campaign editor as part of map editor

**Comment by dydzio0614** [comment]
not sure if useful, but one thing that comes to my mind is "creature set, artifact set, building set" as starting bonuses, where starting bonus icon shows first item in set or special set icon, and by right-clicking and reading bonus description you can get listed all items

example: creature set starting bonus - 5 basilisks, 10 serpent flies, 20 lizardmen
right click says: "5 basilisks, 10 serpent flies, 20 lizardmen", basilisk icon or some special icon is used

**Comment by Fabrice-TIERCELIN** [comment]
Here is a playable campaign working with the `new-pavilion` mod with several issues to discuss:
[Wars_of_the_desert.vcmp.zip](https://github.com/user-attachments/files/18072031/Wars_of_the_desert.vcmp.zip)

1. What is the size of the images to create for the region?
2. Would it be possible to mention the size of the images to create for the region in the [documentation](https://github.com/vcmi/vcmi/blob/develop/docs/modders/Campaign_Format.md)?
3. With `VCMI-branch-develop-3115894`, the region screen is broken, it shows no image and the previous screen is visible. However, pressing `Enter`, the campaign is still playable. I don't know if it's a bug or a misconfiguration of the campaign.
4. How can we create a `.smk` video?
5. Is there any other format than `.smk` supported of the prolog/epilog video?
6. How can we customize the music of the region screen.
7. During prolog, the music is not played. I don't know if it's a bug or a misconfiguration of the campaign.
8. During prolog, the speech is not played. I don't know if it's a bug or a misconfiguration of the campaign.

**Comment by Laserlicht** [comment]
1 - 800x600 (see CamBk file) - other files than background: up to you
3 - never tested it with vcmp - with beta: at least chronicles is working
4 - would not suggest it (see 5.)
5 - yes WEBM with VP8/VP9 codec - suggested to use this by mods
6 - with `"music"` in same structure as for example `"author"`
7 & 8 - How do you have added these files? Currently it's necessary to add these files with a mod. Best way here would possibly wrap vcmp in a mod and add necessary files (music, audio, video, images)

**Comment by IvanSavenko** [comment]
Implemented in 1.7
