### ISSUE TITLE
How to add next layer to game?

### ISSUE THREAD

**Issue by jaicmatija** [vcmi/vcmi#4893]
Heroes 3 has surface and underground layer
how to add next layer to game?
Let's call it "above" It could be next layer to the game maybe some clouds what you could access only by teleporters?
This would add third layer to the game and more space and interesting interactions to it, It could have uniq features like that there is no combat there...

Is is possible to add it to vcmi somehow? mod or feature?

**Comment by jaicmatija** [comment]
Also if this is possible then we could also add 4th layer wich could be space (the final leyer)
There is no oxigen so only non living can go there

**Comment by Olegmods** [comment]
Actually a proposal that came long ago before.

Certainly it's too much pain to make that one, since there are RMG, UI and more stuff needed to make that one.

Plus AFAIK devs already have a lot to do.

**Comment by Macron1Robot** [comment]
At least just multiple subterra levels are easy doable, i think

**Comment by Olegmods** [comment]
I guess it's still needs UI and a lot of code.

**Comment by Alucard648** [comment]
Cloud/space layers are tecnically the same as extra subterranian levels. Many custom maps using above-ground terrains in undergaound layer for extra space on the map and underground terrain in upper layer to simulate caverns without using underground layer. As for high areas, most map builders use impassable water with Magic clouds on top of it to simulate high walkable mountains. HotA Conflux Highlands worked really well in such areas.

**Comment by Laserlicht** [comment]
Open points:
- [x] adding types for layers (instead of directly addressing layer number) - done by  #6619
- [x] fix subterranean gate - done by #6661
- [x] terrains need support for `MapLayerId` instead of fixed "SUB" and "SURFACE" - done by  #6619
- [ ] rmg should handle based on `MapLayerId` (allow to have e.g. multiple undergrounds or changed orders & choosing terrains with `MapLayerId` - allows e.g. sky layer)
- [ ] rmg ui need an input for selecting `MapLayerId` for each layer (or template based?)
- [ ] ui button to change level should be based on `MapLayerId`, not on fixed levels (if e.g. first level is underground instead of second)
- [ ] use `MapLayerId` in some texts (subterranean gate?)
- [ ] layer as source of bonuses (e.g. creatures/hero in sky are slower than on ground) and maybe also limiter
  - but can also archived by terrains for now
- [ ] some minor hardcoded `isSurface` & `isUnderground` (rewards?)

@dydzio0614 @DjWarmonger You may interested in some tasks? Biggest tasks are already done...
